openapi: "3.0.4"
info:
  title: "Book Management API"
  version: "1.0.0"
  description: "API para gerenciar livros"
servers:
  - url: "http://localhost:8080"
    description: "Ambiente local"
tags:
  - name: Books
    description: "Operações relacionadas a livros"

  - name: Authors
    description: "Operações relacionadas a autores"

  - name: Subjects
    description: "Operações relacionadas a assuntos"

paths:
  /api/v1/books:
    get:
      tags:
        - Books
      summary: "List of Books"
      operationId: getAllBooks
      parameters:
        - $ref: '#/components/parameters/NameQuery'
      responses:
        '200':
          description: "Book List"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookResponseData'
    post:
      tags:
        - Books
      summary: "Create a new Book"
      operationId: createBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookRequestDTO'
      responses:
        '201':
          description: "Book created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookResponseData'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'
  /api/v1/books/{id}:
    parameters:
      - $ref: '#/components/parameters/IdParam'
    get:
      tags:
        - Books
      summary: "Find book by ID"
      operationId: getBookById
      responses:
        '200':
          description: "Book found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookResponseData'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      tags:
        - Books
      summary: "Update book by ID"
      operationId: updateBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookRequestDTO'
      responses:
        '200':
          description: "Book updated"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookResponseData'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
        - Books
      summary: "Delete book"
      operationId: deleteBook
      responses:
        '204':
          description: "Book deleted successfully"
        '404':
          $ref: '#/components/responses/NotFound'
  /api/v1/authors:
    post:
      tags:
        - Authors
      summary: "Create a new Author"
      operationId: createAuthor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorRequestDTO'
      responses:
        '201':
          description: "Author created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorResponseData'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'
    get:
      tags:
        - Authors
      summary: "List of Authors"
      operationId: getAllAuthors
      parameters:
        - $ref: '#/components/parameters/NameQuery'
      responses:
        '200':
          description: "Author List"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorResponseData'
  /api/v1/authors/{id}:
    parameters:
      - $ref: '#/components/parameters/IdParam'
    get:
      tags:
        - Authors
      summary: "Find author by ID"
      operationId: getAuthorById
      responses:
        '200':
          description: "Author found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorResponseData'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      tags:
        - Authors
      summary: "Update author by ID"
      operationId: updateAuthor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorRequestDTO'
      responses:
        '200':
          description: "Author updated"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorResponseData'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
        - Authors
      summary: "Delete author"
      operationId: deleteAuthor
      responses:
        '204':
          description: "Author deleted successfully"
        '404':
          $ref: '#/components/responses/NotFound'
  /api/v1/subjects:
    post:
      tags:
        - Subjects
      summary: "Create a new Subject"
      operationId: createSubject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubjectRequestDTO'
      responses:
        '201':
          description: "Subject created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubjectResponseData'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'
    get:
      tags:
        - Subjects
      summary: "List of Subjects"
      operationId: getAllSubjects
      responses:
        '200':
          description: "Subject List"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubjectResponseData'
  /api/v1/subjects/{id}:
    parameters:
      - $ref: '#/components/parameters/IdParam'
    get:
      tags:
        - Subjects
      summary: "Find subject by ID"
      operationId: getSubjectById
      responses:
        '200':
          description: "Subject found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubjectResponseData'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      tags:
        - Subjects
      summary: "Update subject by ID"
      operationId: updateSubject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubjectRequestDTO'
      responses:
        '200':
          description: "Subject updated"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubjectResponseData'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
        - Subjects
      summary: "Delete subject"
      operationId: deleteSubject
      responses:
        '204':
          description: "Subject deleted successfully"
        '404':
          $ref: '#/components/responses/NotFound'

components:
  parameters:
    IdParam:
      name: "id"
      in: "path"
      description: "Book ID"
      required: true
      schema:
        type: integer
        format: int64
    NameQuery:
      name: "name"
      in: "query"
      description: "Name"
      required: false
      schema:
        type: string

  schemas:
    BookRequestDTO:
      type: object
      properties:
        bookCode:
          type: integer
          format: int64
        title:
          type: string
        publisher:
          type: string
        edition:
          type: string
        yearPublication:
          type: string
          example: 1999
        price:
          type: string
          format: decimal
          example: 100.00
        authorsIds:
          type: array
          items:
            type: integer
        subjectsIds:
          type: array
          items:
            type: integer
      required:
        - bookCode
        - title
        - publisher
        - edition
        - yearPublication
        - price
        - authorsIds
        - subjectsIds
    AuthorRequestDTO:
      type: object
      properties:
        name:
          type: string
      required: ["name"]
    SubjectRequestDTO:
      type: object
      properties:
        description:
          type: string
      required: ["description"]

    BookResponseData:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/BookResponseDTO'
    BookResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        bookCode:
          type: string
          example: "BK-123456"
        title:
          type: string
        publisher:
          type: string
        edition:
          type: string
        yearPublication:
          type: string
          example: "2023"
        price:
          type: string
          format: decimal
        authors:
          type: array
          items:
            type: integer
        subjects:
          type: array
          items:
            type: integer
      required:
        - bookCode
        - title
        - publisher
        - edition
        - yearPublication
        - price
        - authors
        - subjects

    AuthorResponseData:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/AuthorResponseDTO'
    AuthorResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required: ["id", "name"]
    SubjectResponseData:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/SubjectResponseDTO'
    SubjectResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required: ["id", "name"]
    Error:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        message:
          type: string
        path:
          type: string
      required: ["code", "message"]

  responses:
    BadRequest:
      description: "Requisição inválida"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: "Recurso não encontrado"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: "Erro interno do servidor"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'