CREATE TABLE TB_BOOK (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BOOK_CODE INTEGER NOT NULL,
  TITLE VARCHAR(40) NOT NULL,
  PUBLISHER VARCHAR(40) NOT NULL,
  EDITION VARCHAR(40),
  PUBLICATION_DATE VARCHAR(4) NOT NULL,
  PRICE NUMERIC(15, 2) NOT NULL
);

CREATE TABLE TB_AUTHOR (
  AUTHOR_CODE BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR(40) NOT NULL
);

CREATE TABLE TB_SUBJECT (
  SUBJECT_CODE BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DESCRIPTION VARCHAR(20) NOT NULL
);

CREATE TABLE TB_BOOK_AUTHOR (
  BOOK_CODE INTEGER NOT NULL,
  AUTHOR_CODE INTEGER NOT NULL,
  PRIMARY KEY (BOOK_CODE, AUTHOR_CODE),
  CONSTRAINT FK_BOOK FOREIGN KEY (BOOK_CODE) REFERENCES TB_BOOK(BOOK_CODE) ON DELETE CASCADE,
  CONSTRAINT FK_AUTHOR FOREIGN KEY (AUTHOR_CODE) REFERENCES TB_AUTHOR(AUTHOR_CODE) ON DELETE CASCADE
);

CREATE TABLE TB_BOOK_SUBJECT (
  BOOK_CODE INTEGER NOT NULL,
  SUBJECT_CODE INTEGER NOT NULL,
  PRIMARY KEY (BOOK_CODE, SUBJECT_CODE),
  CONSTRAINT FK_BOOK FOREIGN KEY (BOOK_CODE) REFERENCES TB_BOOK(BOOK_CODE) ON DELETE CASCADE,
  CONSTRAINT FK_SUBJECT FOREIGN KEY (SUBJECT_CODE) REFERENCES TB_SUBJECT(SUBJECT_CODE) ON DELETE CASCADE
);