CREATE OR REPLACE VIEW VIEW_REPORT_BOOK AS
SELECT
  B.BOOK_CODE,
  B.TITLE AS BOOK_TITLE,
  B.PUBLISHER,
  B.EDITION,
  B.PUBLICATION_DATE AS YEAR_PUBLICATION,
  B.PRICE,
  STRING_AGG(DISTINCT A.NAME, ', ') AS AUTHORS,
  STRING_AGG(DISTINCT S.DESCRIPTION, ', ') AS SUBJECTS
FROM TB_BOOK B
LEFT JOIN TB_BOOK_AUTHOR BA ON BA.BOOK_CODE = B.BOOK_CODE
LEFT JOIN TB_AUTHOR A ON A.AUTHOR_CODE = BA.AUTHOR_CODE
LEFT JOIN TB_BOOK_SUBJECT BS ON BS.BOOK_CODE = B.BOOK_CODE
LEFT JOIN TB_SUBJECT S ON S.SUBJECT_CODE = BS.SUBJECT_CODE
GROUP BY
  B.BOOK_CODE,
  B.TITLE,
  B.PUBLISHER,
  B.EDITION,
  B.PUBLICATION_DATE,
  B.PRICE
ORDER BY
  AUTHORS, B.TITLE;