CREATE OR REPLACE VIEW VIEW_REPORT_BOOK AS
SELECT
  A.AUTHOR_CODE,
  A.NAME AS AUTHOR_NAME,
  B.BOOK_CODE,
  B.TITLE AS BOOK_TITLE,
  B.PUBLISHER,
  B.EDITION,
  B.PUBLICATION_DATE,
  B.PRICE,
  S.SUBJECT_CODE,
  S.DESCRIPTION AS SUBJECT_DESCRIPTION,
  STRING_AGG(DISTINCT A.NAME, ', ') AS AUTHORS,
  STRING_AGG(DISTINCT S.DESCRIPTION, ', ') AS SUBJECTS

FROM TB_AUTHOR A
JOIN TB_BOOK_AUTHOR BA ON BA.AUTHOR_CODE = A.AUTHOR_CODE
JOIN TB_BOOK B ON B.BOOK_CODE = BA.BOOK_CODE
LEFT JOIN TB_BOOK_SUBJECT BS ON BS.BOOK_CODE = B.BOOK_CODE
LEFT JOIN TB_SUBJECT S ON S.SUBJECT_CODE = BS.SUBJECT_CODE

ORDER BY A.NAME, B.TITLE, S.DESCRIPTION;